### ISSUE TITLE
can't delete file in subforder

### ISSUE THREAD

**Issue by zyip** [nib-health-funds/gulp-rev-delete-original#1]
if the original folder has sub-folders, it will throw an error follow:
AssertionError: rimraf: missing path
    at rimraf (/workhome/uding/node_modules/rimraf/rimraf.js:47:3)
    at del (/workhome/uding/node_modules/gulp-rev-delete-original/index.js:18:9)
    at DestroyableTransform._transform (/workhome/uding/node_modules/gulp-rev-delete-original/index.js:57:12)

to fix it, modify the del function in gulp-rev-delete-original/index.js to:

```
var del = function() {
  if(!file.isDirectory())
  {
    rimraf(file.revOrigPath, function(err) {
      if (err) cb(err);
      cb(null, file);
    });
  }
  else
  {
    cb(null);
  }
};
```

**Comment by jameslnewell** [comment]
Good pickup. Want to turn this into a PR?

**Comment by jameslnewell** [comment]
Hi @zyip. 

I'm unable to reproduce this issue with the following setup:

`mkdir -p files/img files/css files/js`
`touch files/img/foo.jpg files/css/index.css files/js/index.js`

``` javascript
var gulp = require('gulp');
var RevAll = require('gulp-rev-all');
var revDel = require('gulp-rev-delete-original');

gulp.task('default', function() {

  var revAll = new RevAll();

  return gulp.src('./files/**/*')
    .pipe(gulp.dest('./dist'))
    .pipe(revAll.revision())
    .pipe(gulp.dest('./dist'))
    .pipe(revDel())
  ;

});
```

If this is still an issue can you please provide steps to reproduce. Thanks.

**Comment by throrin19** [comment]
I have the same issue in my code with subdirectories and this code fix my issue : 

``` javascript
var gulp        = require('gulp'),
    rev         = require('gulp-rev'),
    revDel      = require('gulp-rev-delete-original');

gulp.task('hashres:assets', function () {
    return gulp.src('dist/assets/**/*').pipe(rev())
        .pipe(revDel())
        .pipe(gulp.dest('dist/assets'))
        .pipe(rev.manifest('manifest-assets.json', { merge : true }))
        .pipe(gulp.dest('tmp'));
});
```

The error provides on directory with empty subdirectory.

In my case, I have the directory `dist/assets/flags/4x3/` with files but the parent directory `dist/assets/flags` has no ressources to remove.

**Comment by jameslnewell** [comment]
Can you please include instructions for creating the directory structure you speak of (e.g. listing files with `mkdir` and `touch` are enough).

**Comment by throrin19** [comment]
the directory structure is created in a copy gulp task : 

```
gulp.task('copy:flags', function () {
    return gulp.src('./node_modules/flag-icon-css/flags/**')
        .pipe(gulp.dest('./dist/assets/flags/'));
});
```
