### ISSUE TITLE
Modifying input stream after rev-delete-original seems to be broken

### ISSUE THREAD

**Issue by Francisc** [nib-health-funds/gulp-rev-delete-original#2]
Hi,

I'm running this code:

``` JavaScript
return gulp.src('dist/*.svg')//Get all svg files from dist/
   .pipe(rev())//Revision the files
   .pipe(revDel())//Remove original files, only leaving revved ones
   .pipe(addSrc('dist/**'))//Add all files from dist/ so rev-replace looks everywhere for matches
   .pipe(revReplace())//Replace all occurences of old filenames with revved filenames
   .pipe(gulp.dest('dist/'));//End.
```

The error thrown says that logo.svg doesn't exist (since it was renamed to logo-hashHere.svg) and revDel removed the original one.

Could it be that the next pipe (addSrc) is reached because revDel says its done processing before it actually did finish?

That would explain how `'dist/**'` matches logo.svg initially and the next pipe job can't find it since by that time, revDel finished.

If the `addSrc` pipe is set to `'dist/*.css'`, there's no error and rev+del+replace work.

revReplace is here: https://github.com/jamesknelson/gulp-rev-replace
addSrc is here: https://github.com/urish/gulp-add-src

Thanks.

**Comment by jameslnewell** [comment]
Hi @Francisc,

I've fixed a minor [bug](https://github.com/nib-health-funds/gulp-rev-delete-original/commit/06d151b5c3d70a1094afbd67e23b2d50b7fd5d5c#diff-168726dbe96b3ce427e7fedce31bb0bcL17) in `0.2.0` released as `next` but I'm not confident that it will solve your issue. Can you please try again with `0.2.0` and if that doesn't work create a demo repo with the above setup.

Thanks for reporting the issue!

**Comment by Francisc** [comment]
Thanks James. I'll try to test this, but can't promise anything.

**Comment by jameslnewell** [comment]
@Francisc Closed due to no response. Let me know if its still an issue and I'll reopen it.

**Comment by Francisc** [comment]
Sorry didn't get the time to redo the scenario that was misfiring.
