### ISSUE TITLE
Add LICENSE.md file

### ISSUE THREAD

**Issue by brian-d** [nib-health-funds/gulp-rev-delete-original#4]
In package.json the license is declared as MIT but the license file is missing from the project root. Could you please add the license file? You can find the full text here: http://choosealicense.com/licenses/mit/

Many thanks

**Comment by jameslnewell** [comment]
Can you submit a PR please. Thanks.

**Comment by brian-d** [comment]
Sure thing.

**Comment by brian-d** [comment]
PR's up. Thanks for the quick response.
